title: Jon Curnow
author: Jon Curnow
description: >
  This is Jon's description
header_pages:
  - about.md
plugins:
  - jekyll-relative-links
theme: minima
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
social_links:
     - { platform: twitter,  user_url: "https://twitter.com/curns" }
